### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by btoconnor** [Shopify/activerecord-firewall#9]
Hi,

I went to mess around with this gem in a project, added `gem 'activerecord-firewall'` to my Gemfile and was surprised to find it not work.  I then found that the gem installed via rubygems is a simple Hello World gem.

Is there any intention of flushing this open source gem out to the world? It seems like it could use some documentation updates and a ruby gems update.  I can probably help out with some documentation, but wondering if this project is already abandoned as an open source project.

Thanks

**Comment by rafaelfranca** [comment]
This project is just an experiment and it is not complete yet. We open sourced it so people could be inspired to it but we have no plans right now to support of develop it further.

Thank you for offering to help.
